### ISSUE TITLE
Detail of tokenization, feedforward, and backward processes

### ISSUE THREAD

**Issue by abizard** [time-series-foundation-models/lag-llama#104]
Hello,

I hope this message finds you well. I am currently exploring the Lag-Llama model and I would like to gain a deeper understanding of the tokenization, feedforward, and backward processes within the model. Specifically, could you provide insights on how the tokenization, feedforward, and backward passes are handled in the implementation?

Are there any specific layers or methods in the model where these processes can be observed or logged?

Thank you for your assistance!

**Comment by ashok-arjun** [comment]
Hi, please see the paper: https://arxiv.org/abs/2310.08278 and the code for the implementation. I unfortunately don't have the capacity to discuss it more, sorry.
