### ISSUE TITLE
Forecasting Unknown Data Points

### ISSUE THREAD

**Issue by Jackwannsee** [time-series-foundation-models/lag-llama#106]
Hello, let me preface this by saying **thanks to you and your team** for the great work!

I am a student experimenting with time series forecasting using deep learning methods. Following experimentation, I have noticed that forecasts are not future/ unknown timestamps rather of timestamps that are already in the data. As can be seen in the image. 

![LagLlamaPrediction](https://github.com/user-attachments/assets/5e6e19f2-f27a-4c0d-85fd-85e654d4095d)

I have based my code off of the following [notebook](https://colab.research.google.com/drive/1DRAzLUPxsd-0r8b-o4nlyFXrjw_ZajJJ?usp=sharing#scrollTo=KmLF3yUo9Fnv) alongside synthetic data [(download)](https://github.com/user-attachments/files/17241962/timeseries_data.csv) which follows a predictable path [(image)](https://github.com/user-attachments/assets/905b25b4-b157-41cb-b61f-cda18fe521ef) with hourly intervals. I have made several alterations to the original code as my data doesnt have 9 groups. The code can be found bellow. 

**Hence my question is** how can I forecast timestamps that aren't in the dataset, say predicting 24 hours into the future? Additionally, I am struggling to understand whether the results seen in the image above use the last 96 actual values (96 = prediction length) to generate the forecast in green. 

Note: I was unclear about the `item_id` parameter when calling `PandasDataset.from_long_dataframe` but I see that this was a choice as the data in the notebook has several "groups" for lack of a better word. I bring this up as in my code this is still present (`"item_id="Source"`) and will change it eventually.

```python
### ### ## ## # #
# Imports
### ### ## ## # #
from itertools import islice

from matplotlib import pyplot as plt
import matplotlib.dates as mdates

import torch
from gluonts.evaluation import make_evaluation_predictions, Evaluator
from gluonts.dataset.repository.datasets import get_dataset

from gluonts.dataset.pandas import PandasDataset
import pandas as pd
import os 

from lag_llama.gluon.estimator import LagLlamaEstimator


### ### ## ## # #
# Variables
### ### ## ## # #
DATA_PATH = os.path.join("data", "timeseries_data.csv")
CKPT_PATH = os.path.join("lag-llama.ckpt")

prediction_length = 96
context_length = 32
num_samples = 100  # number of samples sampled from the probability distribution for each time step
use_rope_scaling = True

device = map_location = torch.device('cpu')

target = 'y'
drop_cols = ['x']



### ### ## ## # #
# Prediction Function
### ### ## ## # #
def get_lag_llama_predictions(dataset, prediction_length, device, context_length=32, use_rope_scaling=False, num_samples=100):
    ckpt = torch.load(CKPT_PATH, map_location=torch.device('cpu'))
    estimator_args = ckpt["hyper_parameters"]["model_kwargs"]

    rope_scaling_arguments = {
        "type": "linear",
        "factor": max(1.0, (context_length + prediction_length) / estimator_args["context_length"]),
    }

    estimator = LagLlamaEstimator(
        ckpt_path=CKPT_PATH,
        prediction_length=prediction_length,
        context_length=context_length, # Lag-Llama was trained with a context length of 32, but can work with any context length

        # estimator args
        input_size=estimator_args["input_size"],
        n_layer=estimator_args["n_layer"],
        n_embd_per_head=estimator_args["n_embd_per_head"],
        n_head=estimator_args["n_head"],
        scaling=estimator_args["scaling"],
        time_feat=estimator_args["time_feat"],
        rope_scaling=rope_scaling_arguments if use_rope_scaling else None,

        batch_size=1,
        num_parallel_samples=100,
        device=device,
    )

    lightning_module = estimator.create_lightning_module()
    transformation = estimator.create_transformation()
    predictor = estimator.create_predictor(transformation, lightning_module)

    forecast_it, ts_it = make_evaluation_predictions(
        dataset=dataset,
        predictor=predictor,
        num_samples=num_samples
    )
    forecasts = list(forecast_it)
    tss = list(ts_it)

    return forecasts, tss


### ### ## ## # #
# Data Loading
### ### ## ## # #
df = pd.read_csv(DATA_PATH, index_col=0, parse_dates=True)
df = df.drop(columns=drop_cols)
df["Source"] = 'constant value'

# Set numerical columns as float32
for col in df.columns:
    if df[col].dtype != 'object' and pd.api.types.is_string_dtype(df[col]) == False:
        df[col] = df[col].astype('float32')

dataset = PandasDataset.from_long_dataframe(df, target=target, item_id="Source") #, item_id="Source"


### ### ## ## # #
# Zero-Shot Inference 
### ### ## ## # #
forecasts, tss = get_lag_llama_predictions(
    dataset=dataset, 
    prediction_length=prediction_length, 
    device=device, 
    num_samples=num_samples, 
    context_length=context_length, 
    use_rope_scaling=True
)


### ### ## ## # #
# Plotting Results
### ### ## ## # #
forecast = forecasts[0]
ts = tss[0]

plt.figure(figsize=(10, 5))
date_formater = mdates.DateFormatter('%b, %d')
plt.rcParams.update({'font.size': 15})

# Plot the target and forecast
plt.plot(ts[-4 * prediction_length:].to_timestamp(), label="Temp_C")
forecast.plot(color='g')

plt.xticks(rotation=60)
plt.gca().xaxis.set_major_formatter(date_formater)
plt.title(forecast.item_id)

plt.text(0.5, 0.95, f"prediction_length: {prediction_length},   num_samples: {num_samples},   context_length: {context_length}",
         fontsize=10, ha='center', transform=plt.gca().transAxes)

plt.tight_layout()
plt.legend()
plt.show()
```

Please advise.
Thanks, Jack.

**Comment by ashok-arjun** [comment]
Hi,
we don't have a function to do that.
you need to add (K) timesteps at the end of your dataframe (with dummy values, say random and 0), and use the current function to forecast them

**Comment by Jackwannsee** [comment]
Thanks @ashok-arjun, I'll proceed by adding dummy timestamps. 

Additionally, I wrote a script to export the forecasts to a DataFrame so that I can perform further independent evaluation. The code is shown bellow.

```python
df_results_expanded = pd.DataFrame(data=forecast.samples)
df_results_expanded = df_results_expanded.transpose()

df_results_expanded.columns = [f'Sample{i+1}' for i in range(num_samples)] # values from distribution
df_results_expanded.index = [f'Forecast{i+1}' for i in range(prediction_length)] # prediction for n timestamp

df_results = pd.DataFrame(df_results_expanded.mean(axis=1), columns=['Mean'])
```

In the code I take the forecast object and subset it for the `samples` which to my understanding contains the forecast. The format is a numpy array that contains `num_samples` # of entries and every entry contains `prediction_length` # of elements. Essentially every entry represents a different forecast path. As such I reformatted it so that every entry now represented a forecast timestamp and the entries contained the different samples from the t-distribution. 

As seen in the prediction plot I wanted to make a singular prediction value (green line), to achieve this I took the mean of the reformatted numpy array (samples from the t-distribution). However, the mean values due not correspond to the values on the green line. As such my question is what "aggregation" method does Lag-Llama use to present the different forecast paths? 

Thank you in advance! Jack.

**Comment by ashok-arjun** [comment]
Lag-Llama does probabilistic forecasting (predicts many samples to give the full probability distribution of the output). You can try mean/median, but taking a mean (or median) will not give good performance as Lag-Llama was not trained to give good point forecasts.

**Comment by Jackwannsee** [comment]
Thank you, this is now clear to me. 

All the best,
Jack.
