### ISSUE TITLE
How to use wide csv file for training and testing

### ISSUE THREAD

**Issue by TLF-1234** [time-series-foundation-models/lag-llama#11]
I am trying to use a dataset with lots of timeseries data as specified in the:
https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html Usecase number 3.

I am unsure on how to use this pandas dataset for this model.

Even when using a single timeseries data as mentioned in the another issue, I am unable to get the forecasts and it shows assertion error: (then its blank)

**Comment by ashok-arjun** [comment]
Thanks! A tutorial is coming soon about this after a short recoup! I'll post an update here once the tutorial is out.

**Comment by loveoftheai** [comment]
waiting for that

**Comment by ashok-arjun** [comment]
Hi @TLF-1234  @loveoftheai , we uploaded a new [Colab demo](https://colab.research.google.com/drive/1XxrLW9VGPlZDw3efTvUi0hQimgJOwQG6?usp=sharing) with a tutorial to use a CSV dataset. 

Please check it and let us know if your dataset fits into one of the categories explained there.

**Comment by shahrokhvahabi** [comment]
> > Hi @TLF-1234 @loveoftheai , we uploaded a new [Colab demo](https://colab.research.google.com/drive/1XxrLW9VGPlZDw3efTvUi0hQimgJOwQG6?usp=sharing) with a tutorial to use a CSV dataset.
> > Please check it and let us know if your dataset fits into one of the categories explained there.
> 
> It does seem similar but i am getting: TypeError: object of type 'NoneType' has no len() Type of data: float32 index: pandas._libs.tslibs.timestamps.Timestamp
> 
> I checked for duplicates in data but just can't figure out what is going wrong with this. (There are no Empty Columns or Empty data in between)

Hi. This error arises for the first column, DateTime. To avoid this, reformat this column as @turkalpmd mentioned in this link:
https://github.com/time-series-foundation-models/lag-llama/issues/10. Also, name the first column 'date,' for instance, to facilitate easy access to this column.

data['date'] = pd.to_datetime(data['date'], format='%Y-%m-%d %H:%M:%S')

**Comment by ashok-arjun** [comment]
Hi @TLF-1234 @loveoftheai, checking if this is resolved?

**Comment by ashok-arjun** [comment]
Closing as there is no response. Feel free to reopen if needed!

**Comment by BennetKoerner** [comment]
The Issue also accures if your data has a col named something like "date". In order to solve this simply delete the name of the date col in your lets say csv file. Specify the date col using the index in the pd.read_csv method, as its done in the goolge colab nb.
