### ISSUE TITLE
Request: Comparison to Prophet

### ISSUE THREAD

**Issue by tomtom215** [time-series-foundation-models/lag-llama#12]
First, I just wanted to say this project is very exciting and I plan to follow along with as it begins to mature, so thank you!

My request would be to have a comparison of Lag-Llama and Meta's [Prophet](https://facebook.github.io/prophet/).  I know these are different approaches to time series forecasting, but Prophet is pretty widely used in the industry now, so I think potential users will be attracted to Lag-Llama if they see quantifiable comparisons. 

Ideally this comparison would include tests from both tools against different datasets/sizes to show accuracy and speed of each.

**Comment by ashok-arjun** [comment]
Hi @tomtom215, thanks for the issue.

I agree - a comparison to Prophet would be nice, with different datasets/size and with accuracy and efficiency metrics.

I'd love to see this, but this is not on our roadmap at the moment as we have other projects and priorities.

Would be happy to help compare them if anyone is interested in picking this up! (:

**Comment by ashok-arjun** [comment]
Closing this issue. Feel free to open it again if required :)
