### ISSUE TITLE
Foundation model training details

### ISSUE THREAD

**Issue by mamscience** [time-series-foundation-models/lag-llama#14]
Congrats on this foundation model.

Your publication doesn't mention anything about training time, hardware requirements, and costs. Could you elaborate on this?

Best regards

**Comment by mamscience** [comment]
Always insightful and good to know! Thanks

**Comment by kashif** [comment]
@mamscience  have a look at the colab notebook here for fine-tuning: https://colab.research.google.com/drive/1uvTmh-pe1zO5TeaaRVDdoEWJ5dFDI-pA?usp=sharing
