### ISSUE TITLE
Bad accuracy with the wide dataframe

### ISSUE THREAD

**Issue by TLF-1234** [time-series-foundation-models/lag-llama#17]
I am having bad accuracy (MSE of 2500+)

![image](https://github.com/time-series-foundation-models/lag-llama/assets/160018871/20243035-05e3-4620-a933-69b5b1b07b65)

I am giving the model 10 days worth of data and using the default settings given in the updated colab with a wide dataframe. 
Prediction length = 24

While i see improvement if i increase the prediction length i.e. inplace of predicting for 1 day i predict for 72 time stamps (3 days) that i can get a mse of 400. Which is still high and not as good.

This image is 3 days prediction:
![image](https://github.com/time-series-foundation-models/lag-llama/assets/160018871/375d4e01-d6f5-42cd-97b3-ecdab74b1c39)

Do let me know if i am making a large error when giving this data which is causing this low accuracy.

**Comment by clanert27** [comment]
> Can you please share a demo notebook with the dataset? You can possibly use a dummy dataset in the same style if you want to keep your data private.
> 
> It is also possible that the zero-shot forecasting performance is bad on this dataset. I'd suggest to wait for the finetuning code and try it out then.
@ashok-arjun 
When can we expect the finetuning code to be released?

**Comment by ashok-arjun** [comment]
Apologies for the delay @clanert27, you can expect the full release in 2 weeks approximately.

**Comment by ashok-arjun** [comment]
Hi @clanert27 @TLF-1234 Can you please try finetuning now? We have added a list of instructions and best practices in the README that you could follow.

**Comment by ashok-arjun** [comment]
Closing this issue as it is resolved. Feel free to open it again if required :)
