### ISSUE TITLE
UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by JeremyChou28** [time-series-foundation-models/lag-llama#18]
Hi, thank you very much for your work.

May I ask if the following error occurs when loading pre-trained model parameters while running your code? 
Is it due to the Torch version? My Torch version is 2.2.0.

![image](https://github.com/time-series-foundation-models/lag-llama/assets/62065951/3f8aea95-8366-445b-8dc9-85e5db46248c)

**Comment by ashok-arjun** [comment]
Thanks for the kind words!

Yes it could be because of the torch version. I recommend you create a conda environment and use the specified requirements file and test it.

**Comment by JeremyChou28** [comment]
Thank you for your reply.

In my conda environment, the torch version and other packages meet the requirements.txt.

May I ask what the problem is?

**Comment by ashok-arjun** [comment]
Ah, I'm not sure why in that case. Does the [Colab](https://colab.research.google.com/drive/1XxrLW9VGPlZDw3efTvUi0hQimgJOwQG6?usp=sharing) work well for you?

**Comment by JeremyChou28** [comment]
Yes, it works well on Colab.

The current issue is that it appears on my local conda environment, so I would like to ask you the version numbers of various packages that you can run this code in more details.

The torch version you wrote is >=2.0.0, so each version>=2.0.0 is well?

**Comment by ashok-arjun** [comment]
I see. Sure, I'm happy to share them - apologies I'm currently on vacation and will be back soon; but if you need the version numbers immediately, one idea is to check the version numbers used in Colab after the requirements are installed there.

**Comment by JeremyChou28** [comment]
Thank you, I'll try that first.
Have a nice vacation.

**Comment by ashok-arjun** [comment]
Hi @JeremyChou28, is this resolved?

**Comment by JeremyChou28** [comment]
Thank you, I have resolved this problem. Maybe the version of python should be python>=3.10
