### ISSUE TITLE
True Future Predictions

### ISSUE THREAD

**Issue by bradski7** [time-series-foundation-models/lag-llama#19]
Unable to make future predictions for future timesteps beyond the validation window where there are no known target values. Is that something this model is capable of?

**Comment by ashok-arjun** [comment]
Yes of course - that's something any model should support :) we just need to write some code to support this in the demo.

**Comment by kashif** [comment]
@bradski7  yes since the estimator is a gluonts estimator class, you can call `predict()` method on the predictor

**Comment by ashok-arjun** [comment]
Hi @bradski7, is this resolved?
