### ISSUE TITLE
Training lag-llama with GluonTS dataset reporting error

### ISSUE THREAD

**Issue by CXL-edu** [time-series-foundation-models/lag-llama#22]
The complete code on Colab:
<p align="center">
    <a href="https://colab.research.google.com/drive/1RsW43umnhS_JGuvC0AQkMorNRDpTpLN9?usp=sharing">
        <img src="https://colab.research.google.com/assets/colab-badge.svg">
    </a>
</p>
Using data from Case 1 in GluonTS examples：

https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html#Use-case-1---Loading-data-from-a-long-dataframe

Error：
![lag-llama](https://github.com/time-series-foundation-models/lag-llama/assets/60612507/6db4ca49-69bc-48fd-858b-cfbfaf4d06e3)

**Comment by kashif** [comment]
@CXL-edu should be fixed now... can you try to pull and retrain?

**Comment by CXL-edu** [comment]
When running `Colab`, the encountered error is as follows:
TypeError: `model` must be a `LightningModule` or `torch._dynamo.OptimizedModule`, got `LagLlamaLightningModule`

![error](https://github.com/time-series-foundation-models/lag-llama/assets/60612507/0cecd781-ce69-4d24-98fe-4f76d3ab51cc)

If you could provide a refined and complete example on Colab, I would greatly appreciate it.

**Comment by kashif** [comment]
@CXL-edu  check here: https://colab.research.google.com/drive/1uvTmh-pe1zO5TeaaRVDdoEWJ5dFDI-pA?usp=sharing

**Comment by CXL-edu** [comment]
Thank you for the code. I am having trouble applying it to my data. The code uses the `from gluonts.dataset.repository.datasets import get_dataset` method to get data, such as `dataset = get_dataset("m4_weekly")`. How can I convert the data in `pd.DataFrame` format to the target format? I tried using the `ds = PandasDataset.from_long_dataframe(df, target="target", item_id="item_id")` method, but it didn't work properly.

**Comment by kashif** [comment]
@CXL-edu the gluonts dataformat is quite simple, its is essentially a list of dicts, where each dict needs to have the "Target" and "start" key and the other covariates are optional. So if you make a list of these dicts you can initialize a gluonts dataset via their `ListDataset` class... 

you can also look at any of the datasets from the `get_dataset` to get an idea of the structure of the data

This format is nice (at least for regular time series) as it avoids the unnecessary copy of datetimes and allows for incorporating real-values/catagorical covariates that can be either static or dynamic

**Comment by smrnvdhy** [comment]
@kashif I'd like to follow up on this. I'm exploring finetuning with dynamic/static features with the collab notebook. Started with toy data from gluon here https://ts.gluon.ai/stable/tutorials/data_manipulation/pandasdataframes.html#Include-static-and-dynamic-features

<img width="387" alt="image" src="https://github.com/time-series-foundation-models/lag-llama/assets/61920451/b796c08e-b25f-49cf-8fbd-b47aa2b9448f">
<img width="411" alt="image" src="https://github.com/time-series-foundation-models/lag-llama/assets/61920451/7d989a2d-a203-4fa2-b963-2d4aa83d246f">

Ran into dtype error while checking zero-shot, so I didn't get a chance to try finetuning yet:
<img width="504" alt="image" src="https://github.com/time-series-foundation-models/lag-llama/assets/61920451/8bfb543c-51d5-4983-8051-ad8dcf7341f4">

**Comment by ashok-arjun** [comment]
@smrnvdhy Yes, the current model doesn't support those features.

**Comment by ashok-arjun** [comment]
Hi @CXL-edu Is this resolved?

**Comment by ashok-arjun** [comment]
Closing this issue. Feel free to open it again if required :)
