### ISSUE TITLE
Error. unfortunately the demo colab does not work

### ISSUE THREAD

**Issue by m6129** [time-series-foundation-models/lag-llama#23]
![image](https://github.com/time-series-foundation-models/lag-llama/assets/104712265/1c251860-add8-4965-ae46-7e0396b85ac6)

**Comment by shahrokhvahabi** [comment]
> ![image](https://private-user-images.githubusercontent.com/104712265/309767524-1c251860-add8-4965-ae46-7e0396b85ac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjUwNTQsIm5iZiI6MTcwOTU2NDc1NCwicGF0aCI6Ii8xMDQ3MTIyNjUvMzA5NzY3NTI0LTFjMjUxODYwLWFkZDgtNDk2NS1hZTQ2LTdlMDM5NmI4NWFjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxNTA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWNhYTg5ZTVmZDkxNGEyMGZhN2VkZGIyMmRkYThmNjc4NzUxZjNiZGQ5MDVhN2U0ZGU4ZWEzNmNiMmU5ZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MyhaVy_FjKWBFFMo8rjZf75cSEviTFSrJ0XbZaBHOSU)

You should go to the lag-llama folder before you call LagLlamaEstimator. For instance, 
cd /content/lag-llama.

**Comment by m6129** [comment]
> > ![image](https://private-user-images.githubusercontent.com/104712265/309767524-1c251860-add8-4965-ae46-7e0396b85ac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjUwNTQsIm5iZiI6MTcwOTU2NDc1NCwicGF0aCI6Ii8xMDQ3MTIyNjUvMzA5NzY3NTI0LTFjMjUxODYwLWFkZDgtNDk2NS1hZTQ2LTdlMDM5NmI4NWFjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxNTA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWNhYTg5ZTVmZDkxNGEyMGZhN2VkZGIyMmRkYThmNjc4NzUxZjNiZGQ5MDVhN2U0ZGU4ZWEzNmNiMmU5ZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MyhaVy_FjKWBFFMo8rjZf75cSEviTFSrJ0XbZaBHOSU)
> 
> You should go to the lag-llama folder before you call LagLlamaEstimator. For instance, cd /content/lag-llama.

Thank you for your response. However, changing the directory to the lag-llama folder before calling LagLlamaEstimator does not seem to resolve the issue. The problem might be related to recent changes in the repository (around March 2nd or 3rd, or even earlier).

Regardless, the demo Colab notebook should work without any issues. The error "No module named 'lightning'" appears on any machine, not just in Colab.

I would greatly appreciate if you could provide further guidance on how to properly set up the environment and resolve this error. Please let me know if there are any additional steps I should take or if you have any other suggestions.

Thank you for your time and assistance in this matter.

**Comment by ashok-arjun** [comment]
Sorry, this is related to recent changes in the repository and we are fixing it right now.

**Comment by ashok-arjun** [comment]
Hi @m6129 we have fixed the issue and the colab should work fine now.

Please check it and let us know.

**Comment by m6129** [comment]
> Hi @m6129 we have fixed the issue and the colab should work fine now.
> 
> Please check it and let us know.
Thank You. Now Colab works correctly.
