### ISSUE TITLE
How not to use "item_id"?

### ISSUE THREAD

**Issue by sebasmos** [time-series-foundation-models/lag-llama#24]
I have a dataset with only 1 time series array, so `item_id` is always the same, which is equivalent to not to use it. On the Demo you mention: 
`The item_id is required only when your dataset has multiple series.` However its not working when not specifying this parameter, similarly when using `PandasDataset(dfs_dict, target="target")`. Do you have any suggestions on how to adapt the data on this case? 

Thanks a lot

**Comment by ashok-arjun** [comment]
Hi! I haven't tested it with a single series; maybe it still needs an item_id - I'll check it.

For the time being, can you specify a random (constant) item_id in the item_id column, and see if it works? It shouldn't have any effect on the predictions; it is just for the PandasDataset.

**Comment by shahrokhvahabi** [comment]
> I have a dataset with only 1 time series array, so `item_id` is always the same, which is equivalent to not to use it. On the Demo you mention: `The item_id is required only when your dataset has multiple series.` However its not working when not specifying this parameter, similarly when using `PandasDataset(dfs_dict, target="target")`. Do you have any suggestions on how to adapt the data on this case?
> 
> Thanks a lot

If an error appears you can set item_id to 'A' just to justify the model you have just one time series array. I used it for just one array in 'df_wide' in the third section of the demo code and it works without 'item_id'.

**Comment by kashif** [comment]
i believe if you pull now you should not see this issue

**Comment by ashok-arjun** [comment]
Hi @sebasmos, can you confirm if the issue still exists please?

**Comment by sebasmos** [comment]
Yes thanks, the issue was also my own data, which I hadn't noticed it had some missing values. Part 3 of the demo works for me, thanks a lot!
