### ISSUE TITLE
random seed, how to freeze predictions

### ISSUE THREAD

**Issue by m6129** [time-series-foundation-models/lag-llama#26]
Hello. How do I freeze the predictions? I have a different prediction every time.

**Comment by ashok-arjun** [comment]
Hi, as it is a probabilistic forecasting model, it is expected to give new predictions when you're sampling every time.

If you'd like to have the same samples predicted every time, can you maybe try using a random seed just before sampling?

If that doesn't work, I'm happy to take a look at this again in 2 weeks (I'm busy with releasing everything else for the next 2 weeks). 

Let me know,

Thanks
Arjun

**Comment by m6129** [comment]
Thanks!!
By how using a random seed just before sampling?

**Comment by ashok-arjun** [comment]
I believe before [this line](https://colab.research.google.com/drive/1XxrLW9VGPlZDw3efTvUi0hQimgJOwQG6?usp=sharing#scrollTo=RtVSLpmVSvzr).

**Comment by ashok-arjun** [comment]
Hi @m6129 is this resolved?

**Comment by m6129** [comment]
> Hi @m6129 is this resolved?

Yes, Thanks!
it helped
