### ISSUE TITLE
Holiday consideration

### ISSUE THREAD

**Issue by moghadas76** [time-series-foundation-models/lag-llama#28]
Hi,
Why you did not consider holidays in the preprocessing?
Best regards

**Comment by ashok-arjun** [comment]
Hi @moghadas76, thanks for the comment.

Holiday indicators are typically used as covariates to additionally condition the model on.

The current version of lag-llama does not take in any covariates, although it takes in time features if you note.

We plan to support having covariates such as holiday indicators in a future version of lag-llama, but there's no ETA as of now on its release.

Best,
Arjun
