### ISSUE TITLE
CRPS metric problem

### ISSUE THREAD

**Issue by Shan2L** [time-series-foundation-models/lag-llama#32]
Hi guys, thanks for your effort in this work. I just open this issue to figure out how should I compute the CRPS metric, which is mentioned in your papers. I found that the weighted average quantile loss looks very similar to it. Are they same on values? If not , how could I compute the CRPS? Thanks again.

**Comment by ashok-arjun** [comment]
Hi, CRPS is weighted quantile loss, as in the notebook.

**Comment by Shan2L** [comment]
Thanks for your answer. I guess so, but I saw there are many weight quantiled loss in the notebook. I am not sure which one is can actually stands for CRPS?  Mean weight quantiled loss?  Not sure about that.

**Comment by ashok-arjun** [comment]
There are multiple implementations to compute CRPS, but yes, what we use is mean weighted quantile loss implementation.

**Comment by ashok-arjun** [comment]
Closing this issue as it is resolved. Feel free to open it again if required :)
