### ISSUE TITLE
Embeddings from lag-llama

### ISSUE THREAD

**Issue by onchiptech** [time-series-foundation-models/lag-llama#34]
Hi,

I would like to know the exact location in the lag-llama source code of the last hidden state to capture embeddings. 

Regards,
Surendra

**Comment by ashok-arjun** [comment]
Hi, you could extract the embedding from the model in [this line](https://github.com/time-series-foundation-models/lag-llama/blob/main/lag_llama/model/module.py#L544). The embedding dimension in the current model is 144.
