### ISSUE TITLE
context_length fine-tuning

### ISSUE THREAD

**Issue by arthur-b1** [time-series-foundation-models/lag-llama#41]
Hi, thanks for your great work.
I have a question about the suggested values for context_length, which seem to be powers of 2. Is there a specific reason for this choice, or could we use other values for context_length that are not powers of 2?

**Comment by ashok-arjun** [comment]
Hi! Thanks for the kind words.

We use powers of 2 just because that's the convention. You could use any value.

**Comment by arthur-b1** [comment]
I see, thanks !
