### ISSUE TITLE
How to finetune this model

### ISSUE THREAD

**Issue by zhilif** [time-series-foundation-models/lag-llama#6]
Thanks for releasing this foundation model! I wonder if you have code that demonstrates how to finetune Lag-Llama with custom training data? Thanks!

**Comment by kashif** [comment]
coming up after a short recoup! stay tuned. Essentially since its a gluonts Estimator, one should be able to `estimator.train()` on your data but we need to remove some bespoke fields that were left behind in the lightning callbacks...

**Comment by ArchanaNarayanan843** [comment]
Can we use this model for forecasting on our data as of now?

**Comment by ashok-arjun** [comment]
Yes, as @kashif says, the fine-tuning scripts are coming soon. Scripts to load datasets in custom formats are also coming soon. Thank you for your patience.

**Comment by kashif** [comment]
@shahrokhvahabi try to git pull, I believe its somehow running an older code

**Comment by shahrokhvahabi** [comment]
@kashif I deleted the lag-llama and cloned again it from the repository. But this error occurred again.

**Comment by kashif** [comment]
@shahrokhvahabi its due to the newer lightning version you have... so try do to:

```
!pip uninstall -A gluonts
!pip install -U gluonts[torch]
```

**Comment by shahrokhvahabi** [comment]
@kashif I did but the error is persistent.

**Comment by kashif** [comment]
ah sorry i meant to say:

```
!pip uninstall -A lightning pytorch-lightning gluonts
!pip install -U gluonts[torch]
```

**Comment by shahrokhvahabi** [comment]
> ah sorry i meant to say:
> 
> ```
> !pip uninstall -A lightning pytorch-lightning gluonts
> !pip install -U gluonts[torch]
> ```


Thank you for the reply @kashif . I did as you mentioned above. Could you please give me another suggestion to avoid this error?

**Comment by kashif** [comment]
yeah not sure what more i can do... somehow your setup is sucking in a newer version of lightning

perhaps

```
!pip install lightning==2.1.4 pytorch-lightning==2.1.4
```

**Comment by shahrokhvahabi** [comment]
@kashif Could you please send those files in the model you updated so that I can replace them manually?

**Comment by kashif** [comment]
make a new issue instead of hijacking this one as the original author is getting spammed unnecessarily closing this
