### ISSUE TITLE
Finetune lag-llama using cpu

### ISSUE THREAD

**Issue by mghiani93** [time-series-foundation-models/lag-llama#66]
It is possible finetune lag-llama using cpu?
If it is possible, how can i do? When i change device to cpu i get this error but i don't think is device related...
Thanks for the help and for the amazing work

**Comment by ashok-arjun** [comment]
Hi, what error do you get?

**Comment by ashok-arjun** [comment]
Can you please make a reproducible Colab notebook with your error, and share it here please?

**Comment by ashok-arjun** [comment]
Hi, we just updated the requirements file with a different version of GluonTS. With this update, do you still get the error?

**Comment by mghiani93** [comment]
Hi, this solve the error. Thanks

> Hi, we just updated the requirements file with a different version of GluonTS. With this update, do you still get the error?
