### ISSUE TITLE
ModuleNotFoundError: No module named 'gluonts.torch.modules.loss'

### ISSUE THREAD

**Issue by hydroinfo-prasad** [time-series-foundation-models/lag-llama#67]
![image](https://github.com/time-series-foundation-models/lag-llama/assets/54836143/073b2e8c-67d3-403e-ad6a-43203a5199c4)

**Comment by haseebanwaar** [comment]
It seems gluont recently got updated, you can use
pip install gluonts==0.14.4

**Comment by ashok-arjun** [comment]
This should be solved with the requirements update. Closing this. Please reopen if necessary!
