### ISSUE TITLE
Can the next lottery draw be accurately predicted based on the Taiwan Lottery’s past ten lottery results? Can the accuracy be as high as 95%?

### ISSUE THREAD

**Issue by win10ogod** [time-series-foundation-models/lag-llama#8]
Can the Taiwan Lottery accurately predict the next draw based on the results of the past ten draws with a 95% accuracy rate?
In my experiment, I need to compare the difference and accuracy of specialized forecasting models and general time series forecasting models.

**Comment by ashok-arjun** [comment]
Hi, I do not understand the question correctly: do you have a dataset to use to test this task out on? In that case, you can try Lag-Llama on this task yourself.

Thanks.

**Comment by ashok-arjun** [comment]
Hi @win10ogod, I'm closing this issue as it's stale. Feel free to open it if you would like to reply. Thanks.
