### ISSUE TITLE
the num_samples means

### ISSUE THREAD

**Issue by ympppppp** [time-series-foundation-models/lag-llama#89]
Hello, this work is very helpful to me, but I don't know what the num_samples means in the code, I found that its value seems to affect the prediction result, when it is equal to 1, the prediction result seems to change from interval prediction to point prediction

**Comment by ashok-arjun** [comment]
Yes, that means the number of samples sampled from the T distribution head. When it's set to 1, it becomes a point forecasting model. But note that we trained using the log-likelihood loss, and evaluated for probabilistic prediction (with 100 samples), so performance in point prediction is not guaranteed.

**Comment by ympppppp** [comment]
Hi, author, I still don’t understand the meaning of num_samples in detail. Do you mean that when sampling num_samples=100, the parameters of the t distribution will be calculated based on these 100 sets of prediction results, and then the interval prediction curve will be drawn. When num_samples=1 , which is equivalent to having only one set of prediction results and unable to calculate the parameters of the t distribution, because I see that the final distribution head described in your paper directly outputs the three parameters of the t distribution. These three parameters are obtained based on the results of num_samples sampling. .

**Comment by ashok-arjun** [comment]
The parameters of the T distribution are calculated just once. Then X samples are sampled from the T distribution.
The more the # of samples, the more coverage you have of the distribution.

**Comment by ympppppp** [comment]
> T 分布的参数仅计算一次。然后从 T 分布中抽取 X 个样本。 样本数量越多，分布的覆盖范围就越大。

I now fully understand the meaning of this num_samples, thank you
