### ISSUE TITLE
Why are there no values below 0 for the predicted values

### ISSUE THREAD

**Issue by MXY0202** [time-series-foundation-models/lag-llama#93]
Why are there no values below 0 for the predicted values，
![ETTh2](https://github.com/user-attachments/assets/858a204e-1b66-4159-91ba-ebf890ae1071)
e.g. on the ETTh2 dataset

**Comment by ashok-arjun** [comment]
Are you using `nonnegative_pred_samples=False` when creating the [estimator](https://github.com/time-series-foundation-models/lag-llama/blob/main/lag_llama/gluon/estimator.py#L161)?

**Comment by MXY0202** [comment]
Sorry, I hadn't noticed that parameter, thanks for the help!
